# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=75, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(default=b'O', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WallPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=b'', max_length=400)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 5, 15, 16, 41, 20, 96783))),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_posts', to='wallapp.User')),
            ],
        ),
    ]
