# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0003_auto_20160515_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 15, 19, 2, 8, 866994)),
        ),
    ]
