# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0007_auto_20160515_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='text',
            field=models.TextField(),
        ),
    ]
